# Chapter 2. Pytorch
## Basic Operation

## 0. preparing

In [1]:
#라이브러리 import
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
torch.tensor?

## 1. Tensors
- 데이터 구조(arrays, matrices와 유사)
- 넘파이의 ndarrays와 유사(GPU나 다른 하드웨어에서 실행될 수 있다는 점이 넘파이와 다른 점)
- automatic differentiation



### 데이터 타입에 따른 dtype / tensor 정리   
[pytorch 공식사이트 : TORCH.TENSOR](https://pytorch.org/docs/stable/tensors.html)  
  
| datatype | dtype | CPU tensor | GPU tensor|  
| :-: | :-: | :-: | :-: |  
|32bit float | `torch.float32` or `torch.float` | `torch.FloatTensor` | `torch.cuda.FloatTensor`|  
|64bit float | `torch.float64` or `torch.double` | `torch.DoubleTensor` | `torch.cuda.DoubleTensor`|  
|16bit float | `torch.float16` or `torch.half`  | `torch.HalfTensor` | `torch.cuda.HalfTensor`|  
|32bit int | `torch.int32` or `torch.int` | `torch.IntTensor` | `torch.cuda.IntTensor`|  
|64bit int | `torch.int64` or `torch.long` | `torch.LongTensor` | `torch.cuda.LongTensor`|  
|16bit int | `torch.int16` or `torch.short` | `torch.ShortTensor` | `torch.cuda.Short`|

### Initializing a Tensor
- Directly from data:
`torch.tensor(data)`
- From a Numpy array: `torch.tensor(np_array)`
- With random or constant values:`torch.rand(shape)`,`torch.ones(shape)`
(참고) shape에 `[,]`나 `(,)`는 상관 없음

#### 1.1.1. Directly from data

In [3]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

#### 1.1.2 From a NumPy array

In [4]:
np_array=np.array(data)
x_np=torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### 1.1.3 With random or constant values


In [ ]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(zeros_tensor)

### 1.2. Attributes of a Tensor
- shape
- dtype
- device: 어디에 저장되어 있는가

In [7]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


#### 참고)파이썬 f-문자열
- 문자열 앞에 f 또는 F를 붙여서 f-문자열을 생성
- 중괄호 {} 내에 변수, 표현식, 함수 호출 등을 삽입->이를 문자열로 반환하여 삽입

### 1.3. Operations on Tensors
- 너무 많으니 described `here <https://pytorch.org/docs/stable/torch.html>`__. 여기 들어가서 확인  
- tensors를 GPU로 바꾸기   
 1) `torch.cuda.is_available()`로 확인  
 2)`tenso.to('cuda')`

In [8]:
# 가능하면 tensor를 GPU로 옮기기
if torch.cuda.is_available():
  tensor=tensor.to('cuda')
print(tensor)

tensor([[0.8696, 0.2695, 0.7550, 0.6340],
        [0.9581, 0.6308, 0.4387, 0.6073],
        [0.4711, 0.5854, 0.5121, 0.9183]])


#### 1.3.1 Standard numpy-like indexing and slicing
- 행 추출: `tensor[0]`  
- 열 추출: `tensor[:,0]`  
- 거꾸로 세기: `tensor[:,-1]`

In [10]:
tensor=torch.rand((4,4))
tensor

tensor([[0.4732, 0.1120, 0.9935, 0.7700],
        [0.9574, 0.7020, 0.1079, 0.0139],
        [0.6336, 0.9268, 0.6559, 0.4593],
        [0.8574, 0.5245, 0.3987, 0.6879]])

In [11]:
print('First row:',tensor[0])
print('First column:',tensor[:,0])
print('Last column',tensor[:,-1])
tensor[:,1]=0
print(tensor)

First row: tensor([0.4732, 0.1120, 0.9935, 0.7700])
First column: tensor([0.4732, 0.9574, 0.6336, 0.8574])
Last column tensor([0.7700, 0.0139, 0.4593, 0.6879])
tensor([[0.4732, 0.0000, 0.9935, 0.7700],
        [0.9574, 0.0000, 0.1079, 0.0139],
        [0.6336, 0.0000, 0.6559, 0.4593],
        [0.8574, 0.0000, 0.3987, 0.6879]])


#### 1.3.2 Joining tensors
넘파이와 동일  
`torch.cat([tensor,tensor],axis=0)`  
`torch.stack([tensor,tensor],axis=1)`


In [12]:
t1=torch.cat([tensor,tensor],axis=0)
print(t1.shape)
t2=torch.cat([tensor,tensor],axis=1)
print(t2.shape)

torch.Size([8, 4])
torch.Size([4, 8])


In [13]:
t3=torch.stack([tensor,tensor],axis=0)
print(t3.shape)
print(t3)

t4=torch.stack([tensor,tensor],axis=2)
print(t4.shape)
print(t4)

torch.Size([2, 4, 4])
tensor([[[0.4732, 0.0000, 0.9935, 0.7700],
         [0.9574, 0.0000, 0.1079, 0.0139],
         [0.6336, 0.0000, 0.6559, 0.4593],
         [0.8574, 0.0000, 0.3987, 0.6879]],

        [[0.4732, 0.0000, 0.9935, 0.7700],
         [0.9574, 0.0000, 0.1079, 0.0139],
         [0.6336, 0.0000, 0.6559, 0.4593],
         [0.8574, 0.0000, 0.3987, 0.6879]]])
torch.Size([4, 4, 2])
tensor([[[0.4732, 0.4732],
         [0.0000, 0.0000],
         [0.9935, 0.9935],
         [0.7700, 0.7700]],

        [[0.9574, 0.9574],
         [0.0000, 0.0000],
         [0.1079, 0.1079],
         [0.0139, 0.0139]],

        [[0.6336, 0.6336],
         [0.0000, 0.0000],
         [0.6559, 0.6559],
         [0.4593, 0.4593]],

        [[0.8574, 0.8574],
         [0.0000, 0.0000],
         [0.3987, 0.3987],
         [0.6879, 0.6879]]])


#### 1.3.3 Arithmetic operations
- 행렬 곱: `tensor.matnul(tensor.T)` 혹은 `tensor @ tensor.T`  
- element-wise product: `tensor.mul(tensor)`혹은`tensor*tensor`

In [15]:
y1=tensor@tensor.T
y2=tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[1.8040, 0.5710, 1.3052, 1.3316],
        [0.5710, 0.9285, 0.6837, 0.8735],
        [1.3052, 0.6837, 1.0426, 1.1207],
        [1.3316, 0.8735, 1.1207, 1.3673]])
tensor([[1.8040, 0.5710, 1.3052, 1.3316],
        [0.5710, 0.9285, 0.6837, 0.8735],
        [1.3052, 0.6837, 1.0426, 1.1207],
        [1.3316, 0.8735, 1.1207, 1.3673]])


In [16]:
y3=tensor*tensor
y4=tensor.mul(tensor)

print(y3)
print(y4)

tensor([[2.2395e-01, 0.0000e+00, 9.8706e-01, 5.9295e-01],
        [9.1661e-01, 0.0000e+00, 1.1648e-02, 1.9187e-04],
        [4.0142e-01, 0.0000e+00, 4.3021e-01, 2.1095e-01],
        [7.3520e-01, 0.0000e+00, 1.5896e-01, 4.7317e-01]])
tensor([[2.2395e-01, 0.0000e+00, 9.8706e-01, 5.9295e-01],
        [9.1661e-01, 0.0000e+00, 1.1648e-02, 1.9187e-04],
        [4.0142e-01, 0.0000e+00, 4.3021e-01, 2.1095e-01],
        [7.3520e-01, 0.0000e+00, 1.5896e-01, 4.7317e-01]])


**Single-element tensors**   
단일 텐서의 경우 values를 얻고 싶으면 `item()`붙이기

In [17]:
agg=tensor.sum()
agg_item=agg.item()
print(agg_item, type(agg_item),type(agg))

7.008747577667236 <class 'float'> <class 'torch.Tensor'>


### 1.4 Bridge with NumPy
Tensors와 NumPy memory locations를 공유할 수 있음 (변경이 상호 영향을 주게 됨.)


Tensor to Numpy array   
`텐서이름.numpy()`

In [18]:
t=torch.ones(5)
print(t)
n=t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


tensor 변화가 NumPy에 영향

In [19]:
t[3]=10
print(f"t:{t}")
print(f"n:{n}")

t:tensor([ 1.,  1.,  1., 10.,  1.])
n:[ 1.  1.  1. 10.  1.]


NumPy array to Tensor  
`torch.tensor(넘파이 이름)`

In [20]:
n=np.ones(5)
t=torch.tensor(n)

NumPy변화가 Tensor에 영향

In [24]:
n[1]=3
print(t)
print(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 3. 1. 1. 1.]
