# Numpy

## 5. Joining the array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

Dimension does not change.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr_r = np.concatenate((arr1, arr2), axis=0)

print(arr_r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


###  Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

Dimension increases by 1, but the rule is generally complicated than stack.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np

arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

arr2 = np.array([[9,10], [11,12], [13,14], [15,16]])

arr3 = np.array([[17,18], [19,20], [21,22], [23,24]])


arr = np.stack((arr1, arr2), axis=0)

print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
(2, 4, 2)


In [ ]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

arr2 = np.array([[9,10], [11,12], [13,14], [15,16]])

arr3 = np.array([[17,18], [19,20], [21,22], [23,24]])


arr = np.stack((arr1, arr2, arr3), axis=1)

print(arr)
print(arr.shape)

[[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]
(4, 3, 2)


In [ ]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

arr2 = np.array([[9,10], [11,12], [13,14], [15,16]])

arr3 = np.array([[17,18], [19,20], [21,22], [23,24]])


arr = np.stack((arr1, arr2, arr3), axis=2)

print(arr)
print(arr.shape)

[[[ 1  9 17]
  [ 2 10 18]]

 [[ 3 11 19]
  [ 4 12 20]]

 [[ 5 13 21]
  [ 6 14 22]]

 [[ 7 15 23]
  [ 8 16 24]]]
(4, 2, 3)


In [ ]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5], [6]]) # b.shape=(2, 1)

np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])