# Numpy



## 1. Basic Operations

In [ ]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12] // 파일형식 list
print(storages)

np_storages = np.array(storages)

print(type(np_storages))

SyntaxError: invalid syntax (2267771675.py, line 3)

In [ ]:
# [1, 2, 3, 4] + [1, 2, 3, 4] without using Numpy
storages = [1, 2, 3, 4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)


[2, 4, 6, 8]


In [ ]:
# [1, 2, 3, 4] + [1, 2, 3, 4] using Numpyimport numpy as np
storages = np.array([1, 2, 3, 4])
print(id(storages))
storages += storages
print(storages)
print(id(storages))

storages = storages+storages
print(id(storages)) # id has changed

137303070574992
[2 4 6 8]
137303070574992
137303070575568


In [ ]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print('arr + arr')
print(arr + arr)

# arr - arr
print('arr - arr')
print(arr - arr)

# arr ** 3
print('arr ** 3')
print(arr ** 3)

# 1 / arr
print('1 / arr')
print(1 / arr)


arr + arr
[ 4 10  6  8 16]
arr - arr
[0 0 0 0 0]
arr ** 3
[  8 125  27  64 512]
1 / arr
[0.5        0.2        0.33333333 0.25       0.125     ]


### Reshape

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print(arr.shape)

print(arr.reshape(4, 2)) # You need to understand the mechanism of this transformation.


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
print(arr.reshape(4, -1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1])

[4 5 6]


In [ ]:
arr = np.array([[1, 2 ,3], [4, 5, 6], [7,8,9]])
print(arr[1,2])
# arr[0,1,2] #error

6


In [ ]:
arr = np.array([[1, 2 ,3], [4, 5, 6], [7,8,9]])
print(arr[1:,1:]) # seldomly used

print(arr[[0,2],[0,2]]) # this is not how we expected

print(arr[[0,2],:][:,[0,2]]) # you may alternatively use this.
print(arr[np.ix_([0,2], [0,2])]) # or you may alternatively use this. # I seldomly use this

[[5 6]
 [8 9]]
[1 9]
[[1 3]
 [7 9]]
[[1 3]
 [7 9]]


#### Exercise:
What do you expect about the result of the following code?
```
arr = np.arange(25).reshape(5, 5)
print(arr[[1, 3, 0]])
```

## 2. Slicing

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

print(arr[3:6])

# This is due to broadcasting which we will learn later.
arr[3:6] = 24
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


## View VS Copy

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [ ]:
# Alias (View)

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


arr2 = arr1
arr2[0] = 100

print(arr1)



[1 2 3 4 5]
[100   2   3   4   5]


In [ ]:
# Copy: copy the materials only.
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

print(arr2)

[1 2 3 4 5]
[100   2   3   4   5]


## Comparison with List

List: slicing will do copy

Numpy: slicing will do view

In [ ]:
import numpy as np


arr_List = [x for x in range(10)]
print(arr_List)

arr_List_copy = arr_List[:-4]
arr_List_copy[0] = 100
print(arr_List_copy)
print(arr_List)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[100, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
arr_NumPy = np.arange(10)
print(arr_NumPy)


arr_NumPy_view = arr_NumPy[:-4]
arr_NumPy_view[0] = 100

print(arr_List_copy)
print(arr_NumPy)



[0 1 2 3 4 5 6 7 8 9]
[100, 1, 2, 3, 4, 5]
[100   1   2   3   4   5   6   7   8   9]


In [ ]:
# Recommendation: use .copy() in Numpy.
arr_NumPy = np.arange(10)
arr_NumPy_copy = arr_NumPy[:-4].copy()
arr_NumPy_copy[0] = 100
print(arr_NumPy_copy)
print(arr_NumPy)


[100   1   2   3   4   5]
[0 1 2 3 4 5 6 7 8 9]


### Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [ ]:
arr = np.array([2, 4, 6, 7])
print(arr[np.array([True, True, True, False])])


[2 4 6]


In [ ]:
myindex= arr % 3 == 1
print(myindex)
arr = np.array([2, 4, 6, 7])
print(arr[myindex])

[False  True False  True]
[4 7]


### Exercise:
You are give the following numpy array:
```
a = np.array([1,2,3,4,5,6,7,8,9,10])
```
Do the followings:

1> Copy "a" into "b" so that "a" and "b" are different object.

2> Select odd numbers among a using filtering array.

### Universal Functions

In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

arr_abs = np.abs(arr)
print(arr_abs)


print(np.exp(arr_abs))
print(np.sqrt(arr_abs))


[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [ ]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

new_arr1 = np.unique(arr1)
print(new_arr1)

print(np.union1d(new_arr1, arr2))

print(np.intersect1d(new_arr1, arr2))

print(np.setdiff1d(new_arr1, arr2))


[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


### Random number generation

In [ ]:
import numpy as np

from numpy.random import randint



In [ ]:

# Check np.random.randint
# randint(low, high=None, size=None, dtype=int)
np.random.seed(41) #set seed
arr1 = np.random.randint(0, 11, (5, 2))
print(arr1)

arr2 = np.random.randint(0, 11, size=100)
print(arr2)

# Check np.random.rand
# random.rand(d0, d1, ..., dn)
arr3 = np.random.rand(3,3)
print(arr3)


[[ 0  3]
 [ 2  0]
 [ 1  3]
 [ 9  7]
 [ 5 10]]
[ 8  3  3  2  6  0  4  6  9  3  8  4  7  6  1  5 10  2  1  5  3 10  2 10
  4  1  2  3  4  5  4  5  7  6  2  4  5  8  4 10  6 10  1  4  9  9  5  2
  4  4  4  3  0  7 10  5  2  5  8 10  5 10  2  0  1  7  2  2  8  2  5  2
  8  8  2  1  0  4  1  5  1  1 10  2  7  9  9 10  9  0  1  9  6  7  3  3
 10  2  1  0]
[[0.73726714 0.6825865  0.10020898]
 [0.18844613 0.51500074 0.85539601]
 [0.03261043 0.19205806 0.82956986]]


## Exercise:
1> Generate 100 samples of Gamma distribution of mean 1 and variance 2 and save the samples into the variable "a".

2> Calculate the sample mean and variance of the generated Gamma samples.

Hint 1: Check the following numpy official documents:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.gamma.html
and  wikipedia for Gamma distribution https://en.wikipedia.org/wiki/Gamma_distribution

Hint 2: The following is from numpy official documents.
```
random.gamma(shape, scale=1.0, size=None)
```

## 4. Broadcasting

* This is one of the most important rule in this class.

### axis

Function will be applied along with axis = 0. As a result, axis = 0 will be summarized.

In [ ]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr.shape) #axis 0 means the first element "2" out of (2,3).
print(arr.sum())
print(arr.sum(axis=0))    # array 형태가 아니라
#print(arr.sum(axis=1))


NameError: name 'np' is not defined

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])
print(arr)
# Calulate summation of elements in each rows
print(arr.sum(axis=1))


In [ ]:
arr[1,1]

In [ ]:
import numpy as np

arr = np.arange(10).reshape(2, 5)
print(arr)
print(arr.T) # print(np.transpose(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### Exercise:
You are given the following numpy array:
```
a = np.array([1,5,2,6,8,3])
```
1> Using argsort() method in numpy sort "a" in decreasing order.

2> Using argsort() method in numpy sort "a" in increasing order.

3> Do the same things with sort() method in numpy.

Hint: Use the following official numpy document on argsort():
https://numpy.org/doc/stable/reference/generated/numpy.argsort.html



In [ ]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort() 메서드로 출력하세요
print(arr.argsort())




### axis in sort() method.

In [ ]:
# use sort() to sort numbers within each row in increasing order
arr = np.array([[8, 4, 2], [3, 5, 1], [6, 9, 7]])
print(arr)
arr.sort(axis=1)
print(arr)

In [ ]:
# use sort() to sort numbers within each column in increasing order
arr = np.array([[8, 4, 2], [3, 5, 1]])
arr.sort(axis = 0)
print(arr)

### Matrix calculation

In [ ]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)

print(np.dot(arr, arr))
print(arr @ arr )

# vec를 정의합니다
vec = arr.reshape(-1)
print(vec)

# 변수 vec의 노름을 출력하세요
print(np.linalg.norm(vec))
np.sqrt(np.sum(vec**2)))

### Exercise:

Expaling what are the results of the followings.
```
print(arr.mean(axis=0))
print(arr.sum(axis=1))
print(arr.min())
print(arr.argmax(axis=1))
```


###  Rule of Broadcasting
Rule 1: If number of dim does not match, the shape of one is padded on the left side.

Rule 2: Assume that number of dim match. If shape does not match, the array with shape 1 is stretcted.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

## Example:

Explain the result of the following Python codes.

1> np.arange(3) + 5

2> np.ones((3,3)) + np.arange(3)

3> np.ones((3,3)) + np.arange(3)[:,np.newaxis]

4> np.ones((3,3)) + np.arange(3)[np.newaxis, :]

5> np.arange(3).reshape((3,1)) + np.arange(3)

In [ ]:

x = np.arange(15).reshape(3, 5)
y = np.array([np.arange(5)])
z = x - y


print(z)


x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
y:
[[0 1 2 3 4]]
z:
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


Example 1>
Let $(x_{i,1}, x_{i,2}, x_{i,3})$ to denote the explanatory variable of $i$-th observation, and $(w_1, w_2, w_3)$ to be the corresponding weights. Consider the linear regression where the prediction of $y_i$ is given by
$\widehat{y}_i=x_{i,1}w_1+x_{i,2}w_2+x_{i,3}w_3$. Calculate the loss function
$L=\sum\limits_{i=1}^{n} (x_{i,1}w_1+x_{i,2}w_2+x_{i,3}w_3 w-y_i)^2$ using Python code for given observations:
```
X=np.array([
  [2.0, 3.1, 2.7],
  [4.0, 4.1, 1.9],
  [2.7, 3.1, 5.1],
  [2.5, 1.1, 5.5]
])

W = np.array([-0.1, 0.3, 0.15])

Y= np.array([2.5, 1.9, 3.0, 2.7])
```




Example 2> In neural network, it is common to standardize(normalizing) the explanatory variable $X$ in Example 1. Let's denote the standardized observations as $X^*$ defined by

$x_{i,t}^* = \frac{x_{i,j}-\mu_j}{\sigma_j}$

where $\mu_j$ and $\sigma_j$ are the sample mean and sample standard deviation of the observations $x_{1,j}, \cdots, x_{n,j}$. Calculate $X^*$ using Python.